config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'static_pages#home'
  get 'help'    => 'static_pages#help'
  get 'about'   => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'news' => 'static_pages#news'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  post  'submitcontact' => 'static_pages#submitcontact'
  delete 'logout'  => 'sessions#destroy'
  
  resources :microposts

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy, :index]
  
  resources :users 
  

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    else
      @feed_items = Micropost.paginate(page: params[:page], per_page: 5)
    end
  end

  def submitcontact
    UserMailer.contact_admin(params[:email], params[:comment]).deliver
    flash[:success] = "Thanks for your feedback... we will review it soon and meditate on it."
    redirect_to root_path
  end
  
  def help
  end
  
  def about
  end

  def contact
  end 
  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About</h1>
<p>
  This is the about section. Fill it in real good!
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact Us With Your Nonsense</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
        <form action="/submitcontact" method="post">

            <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

            <label for="email">Your Email</label>
            <input id="email" name="email" size="30" class="form-control" type="text" />

            <label for="comment">Your Message</label>
            <textarea id="comment" name="comment" class="form-control" cols="40" rows="5">Message</textarea>

            <input class="btn btn-lg btn-primary" name="commit" type="submit" value="Send Message" />
        </form>
    </div>
</div>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<h1>Help</h1>
<p>
 This is the help section, to be filled in with helpful tips and one weird tricks.
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
<div class="center jumbotron">
  <h1>Welcome to Generic App</h1>

  <h2>
    This is the finest tagline of all time.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  <%= link_to "Search", microposts_path, class: "btn btn-lg btn-default" %>
</div>

<div class="row">
  <div class="col-md-12">
    <h3>Recent Activity</h3>
    <%= render 'shared/feed' %>
  </div>
</div>

<% end %>

app/views/static_pages/news.html.erb
<% provide(:title, "News") %>
<h1>News</h1>
<p>
  All the news that's fit to print about this glorious website, which is nothing yet. Proudly serving society since 2015.
</p>